version: "3.3"

services:
  nextjs:
    ports:
      - 5000:3000
    build:
      context: /home/ubuntu/Nextdockerapp/nextdockerapp/
      dockerfile: Dockerfile
    restart: always
    volumes:
      - /home/ubuntu/Nextdockerapp/nextdockerapp/:/usr/src/app
      - /usr/src/app/node_modules
      - /usr/src/app/.next
    env_file:
      - .env
